### ISSUE TITLE
Fedora installation error `ModuleNotFoundError: No module named 'opal.rest'`

### ISSUE THREAD

**Issue by gacou54** [obiba/opal-python-client#17]
Dear opal developers,

First of all, thanks for this tool!

I installed the rpm package and got this error (I use Fedora):

```bash
$ opal --help
Traceback (most recent call last):
  File "/usr/bin/opal", line 5, in <module>
    import opal.rest
ModuleNotFoundError: No module named 'opal.rest'
```

I installed opal successfully with pip, but the `opal.rest` import still fails:
```python
>>> import opal
>>> import opal.rest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'opal.rest'
```

Also, may I suggest placing this package on [PyPi](https://pypi.org/) so that it is more easily accessible?

If you want I can take a look since I have experience in python library packaging.

Best regards,
Gabriel

**Comment by ymarcon** [comment]
I have made the installation directory system dependent. But I agree this is not done in a pythonish way. Your contribution to have it in PyPi would be welcomed!

**Comment by gacou54** [comment]
Now I have this error:
```bash
$ opal --help
Traceback (most recent call last):
  File "/home/gacou54/.local/bin/opal", line 4, in <module>
    __import__('pkg_resources').run_script('opal-python-client==2.10.12', 'opal')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/gacou54/.local/lib/python2.7/site-packages/opal_python_client-2.10.12-py2.7.egg/EGG-INFO/scripts/opal", line 5, in <module>
    
  File "build/bdist.linux-x86_64/egg/opal/rest.py", line 43, in <module>
  File "build/bdist.linux-x86_64/egg/opal/core.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/pycurl.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pycurl.py", line 6, in __bootstrap__
ImportError: /home/gacou54/.cache/Python-Eggs/pycurl-7.43.0.6-py2.7-linux-x86_64.egg-tmp/pycurl.so: undefined symbol: PyUnicode_DecodeLocale
```
I think this error is due to Fedora rather than this package. I believe PyCurl has always been problematic on RPM based OS, and even more so now since support for python2 has been removed.

Regarding the package on PyPi, since the whole packaging process involves maven, uploading to PyPi seems quite complex. It might not be worth the time, especially since it's a command-line application rather than a python library.

This can probably be sorted out on my side, but I don't have time.

Thank you,
Gabriel

**Comment by ymarcon** [comment]
The error refers to 'opal-python-client==2.10.12', I think your environment is not clean. Try to purge the installation first and then reinstall.
