### ISSUE TITLE
System package does not install a recent version of protobuf module

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal-python-client#9]
As reported by user when executing opal python client 2.13.0 on ubuntu 16:

```
As part of the creating of a DataSHIELD VM the puppet script use the '/usr/bin/opal', but I am getting a error.

==> default: Notice: /Stage[main]/Opal::Install/Exec[opal_login]/returns: Traceback (most recent call last):
==> default: Notice: /Stage[main]/Opal::Install/Exec[opal_login]/returns:   File "/usr/bin/opal", line 48, in <module>
==> default: Notice: /Stage[main]/Opal::Install/Exec[opal_login]/returns:     import opal.analysis_plugin
==> default: Notice: /Stage[main]/Opal::Install/Exec[opal_login]/returns:   File "/usr/lib/python2.7/dist-packages/opal/analysis_plugin.py", line 10, in <module>
==> default: Notice: /Stage[main]/Opal::Install/Exec[opal_login]/returns:     from google.protobuf.json_format import Parse
==> default: Notice: /Stage[main]/Opal::Install/Exec[opal_login]/returns: ImportError: No module named json_format
==> default: Error: 'opal system --opal http://localhost:8080 --user administrator --password 'XXXX' --conf' returned 1 instead of one of [0]
==> default: Error: /Stage[main]/Opal::Install/Exec[opal_login]/returns: change from 'notrun' to ['0'] failed: 'opal system --opal http://localhost:8080 --user administrator --password 'XXXX' --conf' returned 1 instead of one of [0]
```

The `protobuf` module installed by the `python-protobuf` debian package appears to be quite old:

```
$ pip show protobuf
---
Metadata-Version: 1.0
Name: protobuf
Version: 2.6.1
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: protobuf@googlegroups.com
Author-email: protobuf@googlegroups.com
License: New BSD License
Location: /usr/lib/python2.7/dist-packages
``` 

The command `pip install --upgrade protobuf` should fix the problem of the outdated system package.

**Comment by ymarcon** [comment]
The `json_format` module first appeared in [protobuf 2.7.0 branch](https://github.com/protocolbuffers/protobuf/tree/2.7.0/python/google/protobuf).

**Comment by ymarcon** [comment]
Could we not depend on json_format?

**Comment by meek0** [comment]
It is only used in the `analysis-plugin` command. Might be removable.

**Comment by meek0** [comment]
Created PR #10 which removes `json_format` import.
